name: Deploy App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build app
        run: |
          echo "Running docker build..."
          docker build -t ${{ vars.REPO_URL }}:latest .
          docker push ${{ vars.REPO_URL }}:latest
  

  sonar_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sonar scan
        run: |
          echo "Running sonar"
          echo "Done!"

  terraform_apply:
    runs-on: ubuntu-latest
    needs: sonar_scan
    steps:
      - name: Terraform apply
        run: |
          echo "Running terraform plan..."
          echo "Running terraform apply..."
          echo "Done!"