name: Deploy App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Running docker build..."
          echo "Running docker push image..."
          echo "Done!"

  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Sonar scan
        run: |
          echo "Running sonar"
          echo "Done!"

  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform apply
        run: |
          echo "Running terraform plan..."
          echo "Running terraform apply..."
          echo "Done!"