name: Deploy

on:
  workflow_dispatch:

jobs:
  sonar_scan: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Validate Maven configuration
        run: mvn validate

      - name: Install dependencies and build
        run: mvn clean install -DskipTests

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=vadebicicleta \
          -Dsonar.organization=es2 \
          -Dsonar.host.url=https://sonarcloud.io

  build:
    runs-on: ubuntu-latest
    needs: sonar_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build app
        run: |
          echo "Running docker build..."
          docker build -t ${{ vars.REPO_URL }}:latest .
          docker push ${{ vars.REPO_URL }}:latest

  apply:
    runs-on: ubuntu-latest
    needs: build
    env:
      TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform apply
        run: |
          cd terraform/
          terraform init
          terraform plan
          terraform apply -auto-approve
          echo "Done!"