name: Manual steps

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Select step to run"
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - apply
          - destroy
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
  build:
    if: ${{ github.event.inputs.job == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build app
        run: |
          echo "Running docker build..."
          docker build -t ${{ vars.REPO_URL }}:latest .
          docker push ${{ vars.REPO_URL }}:latest

  apply:
    if: ${{ github.event.inputs.job == 'apply' }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform apply
        run: |
          cd terraform/
          terraform plan
          echo "Done!"

  destroy:
    if: ${{ github.event.inputs.job == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Terraform destroy
        run: |
          echo "Running terraform plan..."
          echo "Running terraform destroy..."
          echo "Done!"