name: Manual steps

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Select step to run"
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - apply
          - destroy
jobs:
  build:
    if: ${{ github.event.inputs.job == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Running docker build..."
          echo "Running docker push image..."
          echo "Done!"

  apply:
    if: ${{ github.event.inputs.job == 'apply' }}
    runs-on: ubuntu-latest
    steps:
      - name: Terraform apply
        run: |
          echo "Running terraform plan..."
          echo "Running terraform apply..."
          echo "Done!"

  destroy:
    if: ${{ github.event.inputs.job == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Terraform destroy
        run: |
          echo "Running terraform plan..."
          echo "Running terraform destroy..."
          echo "Done!"